#
# Example for a web scan using PowerShell;
#
trigger: none

# API key variables are stored in a Library
#variables:
#- group: "CxOne Variables"

pool:
  name: Default

jobs:
- job: build
  displayName: 'CxOne Scan'

  steps:
  # Use PowerShell to do the heavy lifting

  # Publish the contents of the output directory as artifacts

  - task: Application security testing@2023
    inputs:
      projectName: 'Paras_Test'
      enableProxy: false
      enableSastScan: true
      CheckmarxService: 'CxSAST'
      fullTeamName: '\CxServer'
      enableDependencyScan: true
      dependencyServerURL: 'CxSCA'
      dependencyFolderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules, test'
      scaTeam: '\CxServer'
      isEnableScaResolver: true
      pathToScaResolver: 'D:\ScaResolver\2.2.5\'
      scaResolverAddParameters: '-s D:\Azure Agent\_work\4\s -n Paras_Test -r D:\Azure Agent\_work\4\s\report\ --log-level Debug'

