#
# Example for a web scan using PowerShell;
#
trigger: none

# API key variables are stored in a Library
#variables:
#- group: "CxOne Variables"

pool:
  name: Default

jobs:
- job: build
  displayName: 'CxOne Scan'

  steps:
  # Use PowerShell to do the heavy lifting

  # Publish the contents of the output directory as artifacts

  - task: Application security testing@2023
    inputs:
      projectName: 'Paras_Test'
      enableProxy: false
      enableSastScan: true
      CheckmarxService: 'CxSAST'
      fullTeamName: '\CxServer'
      enableDependencyScan: true
      dependencyServerURL: 'CxSCA'
      scaTeam: '\CxServer'
      isEnableScaResolver: true
      pathToScaResolver: 'D:\ScaResolver\2.2.5\ScaResolver.exe'

