# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'ast'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'test_naftali'
    additionalParams: '--debug,--sast-preset-name,"ASA Premium",--scan-types,sca,sast,iac-security,--sca-last-sast-scan-time=1,--sca-exploitable-path=true,--report-format,pdf,--report-pdf-email,akash.singh@checkmarx.com'