#
# Example for a DAST web scan using PowerShell;
#
trigger: none

# API key variables are stored in a Library
#variables:
#- group: "CxOne DAST Variables"

pool:
  name: Default

jobs:
- job: build
  displayName: 'Initiate DAST scan'

  steps:
  # Use PowerShell to do the heavy lifting

  # Publish the contents of the output directory as artifacts

  - task: Checkmarx AST@2
    inputs:
      CheckmarxService: 'CxOne'
      projectName: '$(Build.Repository.Name)'
      branchName: '$(Build.SourceBranchName)'
      tenantName: 'dp_wp_account'
      additionalParams: '--sca-resolver "D:\ScaResolver\2.2.5\ScaResolver.exe"'

