#
# Example for a DAST web scan using PowerShell;
#
trigger: none

# API key variables are stored in a Library
#variables:
#- group: "CxOne DAST Variables"

pool:
  name: Default

jobs:
- job: build
  displayName: 'Initiate DAST scan'

  steps:
  # Use PowerShell to do the heavy lifting

  # Publish the contents of the output directory as artifacts

  - task: Application security testing@2023
    inputs:
      projectName: '00182619'
      enableProxy: false
      enableSastScan: true
      #Checkmarks CxSAST service connection
      CheckmarxService: 'CxSAST'
      enableDependencyScan: true
      #Checkmarks CxSCA  service connection
      dependencyServerURL: 'CxSCA'
      scaTeam: '\CxServer'

      

  
  