# Starter pipeline
- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'ast'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'test_naftali'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Application security testing@2022
  inputs:
    projectName: 'test5'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'sast'
    fullTeamName: 'CxServer'
    enableDependencyScan: false
