name: Checkmarx Scan

on:
  push:
    branches:
    - main
    - master

jobs:
  run_checkmarx:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
        # Checks out the GitHub repository to GITHUB_WORKSPACE so that subsequent steps could act on it
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: test_naftali
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id:  Akash_action
          cx_client_secret: vWAHB1AXfz91I1jY4rCwTfPprPkZ3YaG
          additional_params: --scs-repo-url https://github.com/WebGoat/WebGoat.git --report-format sarif --output-path . --scan-types sast,iac-security,sca,api-security
      - name: Upload Checkmarx SARIF File
        uses: actions/upload-artifact@v4
        with:
          name: Checkmarx Report
          file: cx_result.sarif
