# This is a basic workflow to create GitHub Issues using the Checkmarx CxFlow GitHub Action.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_URL
#   - CHECKMARX_USER
#   - CHECKMARX_PASSWORD
#   - CHECKMARX_CLIENT_SECRET
#   - GH_TOKEN
#
# Update the 'team' field to reflect the team name used in Checkmarx.
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action

name: CxFlow-GitHub-Issue-Push
# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches:
    - main
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - Ubuntu is required as Docker is leveraged for the action
    runs-on: ubuntu-latest
    # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.4
      with:
        project: ${{ github.repository }}
        team: CxServer/SP/APAC
        checkmarx_url: https://cxprivatecloud.checkmarx.net/  # To be stored in GitHub Secrets.
        checkmarx_username: akash.singh@checkmarx.com  # To be stored in GitHub Secrets.
        checkmarx_password: Santa@11feb  # To be stored in GitHub Secrets.
        checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C  # To be stored in GitHub Secrets.
        github_token: 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  # To be stored in GitHub Secrets.
        incremental: false
        scanners: sast
        bug_tracker: GitHub
        params: --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --cx-flow.filterSeverity --cx-flow.filterCategory
